export let products = [
  {
    id: 1,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/1.png",
    cartStatus: false,
  },
  {
    id: 2,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/2.png",
    cartStatus: false,
  },
  {
    id: 3,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/3.png",
    cartStatus: false,
  },
  {
    id: 4,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/4.png",
    cartStatus: false,
  },
  {
    id: 5,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/5.png",
    cartStatus: false,
  },
  {
    id: 6,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/6.png",
    cartStatus: false,
  },
  {
    id: 7,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/7.png",
    cartStatus: false,
  },
  {
    id: 8,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/8.png",
    cartStatus: false,
  },
  {
    id: 9,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/9.png",
    cartStatus: false,
  },
  {
    id: 10,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/10.png",
    cartStatus: false,
  },
  {
    id: 11,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/11.png",
    cartStatus: false,
  },
  {
    id: 12,
    name: "Nike Sneakers",
    price: "112.55$",
    image: "../assets/product-images/12.png",
    cartStatus: false,
  },
];
